[package]
name = "Vesting"
version = "0.0.1"

[addresses]
std = "0x1"
Vesting = "0x225b149b3bfc3caabcbb7edf8c855636c0c00131226127e35545556aaf325278"

[dependencies]
MoveStdlib = { local = "../minimarket/vendor/aptos-core/aptos-move/framework/move-stdlib" }
